// ==========================================================================
// Ergalics Studio — sweep design expansion (pure TS)
//
// expandPlan turns a SweepPlan into the deterministic list of design points
// and repeated cells the runner must execute:
//   - all-grid/list axes  -> full Cartesian product
//   - all-lhs axes        -> Latin hypercube (one stratum per dimension row)
// Mixed lhs/grid plans are rejected — they have no unambiguous sample size.
// ==========================================================================

import { mulberry32 } from '@/core/repro/random';
import type { SweepAxis, SweepCell, SweepPlan } from './types';

export type AxisValue = number | string;

/** Inclusive evenly spaced levels (mirrors numpy.linspace). */
export function linspace(from: number, to: number, steps: number): number[] {
  if (!Number.isFinite(from) || !Number.isFinite(to)) {
    throw new Error('sweep grid bounds must be finite numbers');
  }
  if (!Number.isInteger(steps) || steps < 2) {
    throw new Error('sweep grid requires steps >= 2');
  }
  if (from === to) {
    return new Array(steps).fill(from);
  }
  const out: number[] = new Array(steps);
  const span = to - from;
  for (let i = 0; i < steps; i += 1) {
    out[i] = from + (span * i) / (steps - 1);
  }
  return out;
}

function validateAxis(axis: SweepAxis): void {
  if (!axis.param || typeof axis.param !== 'string') {
    throw new Error('sweep axis is missing its param path');
  }
  if (axis.mode === 'grid') {
    if (!axis.grid) throw new Error(`axis ${axis.param}: grid mode needs a grid spec`);
    linspace(axis.grid.from, axis.grid.to, axis.grid.steps);
  } else if (axis.mode === 'list') {
    if (!axis.list || axis.list.length === 0) {
      throw new Error(`axis ${axis.param}: list mode needs at least one value`);
    }
  } else if (axis.mode === 'lhs') {
    if (!axis.lhs || !Number.isInteger(axis.lhs.n) || axis.lhs.n < 1) {
      throw new Error(`axis ${axis.param}: lhs mode needs n >= 1`);
    }
  } else {
    throw new Error(`axis ${axis.param}: unknown mode`);
  }
}

/** Explicit levels for a grid or list axis. */
export function axisLevels(axis: SweepAxis): AxisValue[] {
  validateAxis(axis);
  if (axis.mode === 'grid') return linspace(axis.grid!.from, axis.grid!.to, axis.grid!.steps);
  if (axis.mode === 'list') return [...axis.list!];
  throw new Error(`axis ${axis.param}: lhs levels are generated by expandLhs, not axisLevels`);
}

/** Fisher–Yates shuffle with a seeded RNG. */
function shuffled(n: number, rand: () => number): number[] {
  const perm = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    const a = perm[i]!;
    const b = perm[j]!;
    perm[i] = b;
    perm[j] = a;
  }
  return perm;
}

/**
 * Latin-hypercube rows over the LHS axes. Every row lands in a distinct
 * stratum along every dimension; jitter is the stratum midpoint (median LHS),
 * which keeps the design deterministic and symmetric.
 */
export function expandLhs(axes: SweepAxis[]): Array<Record<string, number>> {
  const first = axes[0];
  if (!first?.lhs) return [];
  const n = first.lhs.n;
  if (axes.some((a) => a.lhs!.n !== n)) {
    throw new Error('lhs axes must share the same n');
  }
  const rows: Array<Record<string, number>> = Array.from({ length: n }, () => ({}));
  axes.forEach((axis, dim) => {
    const spec = axis.lhs!;
    const from = spec.from ?? 0;
    const to = spec.to ?? 1;
    // Per-dimension stream so adding/removing an axis does not shift others.
    const rand = mulberry32((spec.seed >>> 0) + Math.imul(dim + 1, 0x9e3779b9));
    const strata = shuffled(n, rand);
    for (let row = 0; row < n; row += 1) {
      const midpoint = (strata[row]! + 0.5) / n;
      rows[row]![axis.param] = from + (to - from) * midpoint;
    }
  });
  return rows;
}

/** Full Cartesian product; the last axis varies fastest. */
export function cartesian(
  axes: SweepAxis[],
  levels?: Array<AxisValue[]>,
): Array<Record<string, AxisValue>> {
  const valueSets = levels ?? axes.map(axisLevels);
  let rows: Array<Record<string, AxisValue>> = [{}];
  axes.forEach((axis, i) => {
    const next: Array<Record<string, AxisValue>> = [];
    for (const row of rows) {
      for (const value of valueSets[i]!) {
        next.push({ ...row, [axis.param]: value });
      }
    }
    rows = next;
  });
  return rows;
}

/** Canonical cell identity: params keys sorted + repeat index. */
export function cellKey(params: Record<string, AxisValue>, rep: number): string {
  const keys = Object.keys(params).sort();
  return `${keys.map((k) => `${k}=${params[k]}`).join('|')}#r${rep}`;
}

/**
 * Expand a plan into the full (un-executed) cell list. Repeat r of a point
 * gets its own deterministic seed derived from plan id + cell key.
 */
export function expandPlan(plan: SweepPlan): Array<Omit<SweepCell, 'value' | 'runId' | 'durationMs'>> {
  if (!Array.isArray(plan.axes) || plan.axes.length === 0) {
    throw new Error('sweep plan needs at least one axis');
  }
  if (plan.axes.length > 3) {
    throw new Error('sweep plan supports at most 3 axes');
  }
  plan.axes.forEach(validateAxis);
  const repeats = Math.max(1, Math.floor(plan.repeats ?? 1));

  const modes = new Set(plan.axes.map((a) => a.mode));
  if (modes.has('lhs') && modes.size > 1) {
    throw new Error('sweep plan cannot mix lhs axes with grid/list axes');
  }

  const points = modes.has('lhs')
    ? (expandLhs(plan.axes) as Array<Record<string, AxisValue>>)
    : cartesian(plan.axes);

  const cells: Array<Omit<SweepCell, 'value' | 'runId' | 'durationMs'>> = [];
  for (let rep = 0; rep < repeats; rep += 1) {
    for (const params of points) {
      const key = cellKey(params, rep);
      // Stable u32 seed per (plan, cell, repeat).
      let h = 0x811c9dc5;
      const blob = `${plan.id}:${key}`;
      for (let i = 0; i < blob.length; i += 1) {
        h ^= blob.charCodeAt(i);
        h = Math.imul(h, 0x01000193);
      }
      cells.push({ key, params: { ...params }, rep, seed: h >>> 0 });
    }
  }
  return cells;
}

/**
 * Apply a dotted parameter path onto a nested plain object.
 * e.g. setPath({}, 'lbm.viscosity', 0.1) -> { lbm: { viscosity: 0.1 } }
 */
export function setPath(
  target: Record<string, unknown>,
  path: string,
  value: unknown,
): Record<string, unknown> {
  const parts = path.split('.');
  let node = target;
  for (let i = 0; i < parts.length - 1; i += 1) {
    const key = parts[i]!;
    if (typeof node[key] !== 'object' || node[key] === null) {
      node[key] = {};
    }
    node = node[key] as Record<string, unknown>;
  }
  node[parts[parts.length - 1]!] = value;
  return target;
}

/** Read a dotted path; a leading `metrics.` / `outputs.` segment is optional. */
export function getPath(value: unknown, path: string): unknown {
  const parts = path.split('.');
  let node: unknown = value;
  for (const part of parts) {
    if (node === null || node === undefined || typeof node !== 'object') return undefined;
    node = (node as Record<string, unknown>)[part];
  }
  return node;
}

/**
 * Extract the configured metric from a run outcome. Tries the configured path
 * as-is, then with a leading `metrics.` prefix.
 */
export function extractMetric(
  outcome: { metrics?: Record<string, number> } & Record<string, unknown>,
  metricPath: string,
): number {
  const direct = getPath(outcome, metricPath);
  if (typeof direct === 'number' && Number.isFinite(direct)) return direct;
  if (!metricPath.startsWith('metrics.')) {
    const prefixed = getPath(outcome, `metrics.${metricPath}`);
    if (typeof prefixed === 'number' && Number.isFinite(prefixed)) return prefixed;
  }
  // Last resort: top-level metrics entry by final segment.
  const tail = metricPath.split('.').pop()!;
  const fromMetrics = outcome.metrics?.[tail];
  if (typeof fromMetrics === 'number' && Number.isFinite(fromMetrics)) return fromMetrics;
  return Number.NaN;
}
