/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_computekernel_free: (a: number, b: number) => void;
export const __wbg_computequeue_free: (a: number, b: number) => void;
export const __wbg_kerneldescriptor_free: (a: number, b: number) => void;
export const computekernel_compile: (a: any, b: number) => [number, number, number];
export const computekernel_label: (a: number) => [number, number];
export const computekernel_pipeline: (a: number) => any;
export const computequeue_submit: (a: number, b: number, c: number) => void;
export const kerneldescriptor_entry_point: (a: number) => [number, number];
export const kerneldescriptor_label: (a: number) => [number, number];
export const kerneldescriptor_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const kerneldescriptor_workgroup_size: (a: number) => [number, number];
export const computequeue_new: (a: any) => number;
export const __wbg_gpudevicemanager_free: (a: number, b: number) => void;
export const __wbg_gpuinfo_free: (a: number, b: number) => void;
export const core_version: () => [number, number];
export const detect_file_kind: (a: number, b: number) => number;
export const gpudevicemanager_acquire: (a: any, b: number) => any;
export const gpudevicemanager_device: (a: number) => any;
export const gpudevicemanager_info: (a: number) => number;
export const gpuinfo_backend: (a: number) => [number, number];
export const gpuinfo_name: (a: number) => [number, number];
export const log: (a: number, b: number) => void;
export const start: () => void;
export const wasm_bindgen_88c4dfa59b813fd8___convert__closures_____invoke___wasm_bindgen_88c4dfa59b813fd8___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_88c4dfa59b813fd8___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_88c4dfa59b813fd8___convert__closures_____invoke___wasm_bindgen_88c4dfa59b813fd8___sys__JsNullable_web_sys_15a71ddd799efe3c___features__gen_GpuAdapter__GpuAdapter___core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_88c4dfa59b813fd8___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_88c4dfa59b813fd8___convert__closures_____invoke___wasm_bindgen_88c4dfa59b813fd8___sys__JsNullable_web_sys_15a71ddd799efe3c___features__gen_GpuAdapter__GpuAdapter___core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_88c4dfa59b813fd8___JsError___true__2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_88c4dfa59b813fd8___convert__closures_____invoke___js_sys_c4eaf1aca999235d___Function_fn_wasm_bindgen_88c4dfa59b813fd8___JsValue_____wasm_bindgen_88c4dfa59b813fd8___sys__Undefined___js_sys_c4eaf1aca999235d___Function_fn_wasm_bindgen_88c4dfa59b813fd8___JsValue_____wasm_bindgen_88c4dfa59b813fd8___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
