// ==========================================================================
// FR-20 — PWA panel for the Settings page.
//
// Contract for the host page (SettingsPage mounts this as <PwaPanel />):
//   props.classPrefix?: string  — extra class on the root <section>
//   Everything else is self-contained; all copy goes through `pwa.*` i18n
//   keys (src/i18n/dicts/pwa.ts).
// ==========================================================================

import { useEffect, useState } from 'react';
import { useT } from '@/i18n';
import {
  NETWORK_RESOURCES,
  getInstallPrompt,
  isOnline,
  isStandalone,
  requestInstall,
  subscribeInstallable,
  subscribeOnline,
  swSupported,
} from '@/core/pwa';

export interface PwaPanelProps {
  classPrefix?: string;
}

/** Build the honest offline starter document (markdown + zero-config scripts). */
function offlineStarterText(): string {
  const origin = typeof window !== 'undefined' ? window.location.origin + (window.location.pathname ?? '/') : '';
  return [
    '# Ergalics Studio — Offline Edition Starter',
    '',
    'This file is downloaded from the app (Settings → Offline & Install).',
    'It documents how to run the workstation fully offline.',
    '',
    '## 1. Get the offline build',
    '',
    `- The live app is served from: ${origin || 'https://…/app/'}`,
    '- Option A (recommended): install this page as an app (browser address-bar',
    '  install button, or the Install button in Settings). The service worker',
    '  caches the shell + core chunks, so relaunching works offline.',
    '- Option B: clone the repository and run `npm ci && npm run build:web`;',
    '  the `dist/` folder is the complete single-folder offline edition.',
    '',
    '## 2. Run the folder offline (double-click / LAN)',
    '',
    'Save one of these scripts next to the build output and run it:',
    '',
    '### start-offline.bat (Windows, zero config)',
    '```bat',
    '@echo off',
    'start http://localhost:8788',
    'python -m http.server 8788',
    '```',
    '',
    '### start-offline.sh (macOS / Linux)',
    '```sh',
    '#!/bin/sh',
    '(sleep 1 && xdg-open http://localhost:8788 2>/dev/null || open http://localhost:8788) &',
    'python3 -m http.server 8788',
    '```',
    '',
    '## 3. What works offline',
    '',
    '- Example projects, notebooks, plotting, statistics, SQL (DuckDB-WASM),',
    '  block coding, figures, reports — everything bundled in the build.',
    '- Python (Pyodide) / R (webR) / Blockly engines after their FIRST online',
    '  use (the service worker caches them from then on).',
    '',
    '## 4. What always needs network',
    '',
    '- Pyodide CDN fallback (cdn.jsdelivr.net) when the vendored copy is absent',
    '- Model weights imported from external URLs',
    '- External links (GitHub, online help)',
    '',
    'License: MIT. Generated by Ergalics Studio FR-20.',
  ].join('\n');
}

async function downloadStarter(): Promise<void> {
  const blob = new Blob([offlineStarterText()], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'ergalics-offline-starter.md';
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function PwaPanel({ classPrefix }: PwaPanelProps) {
  const t = useT();
  const [, bump] = useState(0);
  const [swState, setSwState] = useState<'unknown' | 'none' | 'ready' | 'pending'>('unknown');
  const [downloaded, setDownloaded] = useState(false);
  const [installOutcome, setInstallOutcome] = useState<'accepted' | 'dismissed' | 'unavailable' | null>(null);

  useEffect(() => {
    const un1 = subscribeOnline(() => bump((n) => n + 1));
    const un2 = subscribeInstallable(() => bump((n) => n + 1));
    return () => {
      un1();
      un2();
    };
  }, []);

  useEffect(() => {
    if (!swSupported() || typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
      setSwState('none');
      return;
    }
    let cancelled = false;
    void navigator.serviceWorker.getRegistration().then((reg) => {
      if (cancelled) return;
      if (!reg || !reg.active) setSwState(reg ? 'pending' : 'none');
      else setSwState('ready');
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const online = isOnline();
  const standalone = isStandalone();
  const installable = getInstallPrompt() !== null;

  return (
    <section className={`card settings-section${classPrefix ? ` ${classPrefix}-pwa` : ''}`}>
      <h2 className="settings-section-title">{t('pwa.section_title')}</h2>
      <p className="settings-label">{t('pwa.intro')}</p>

      <h3 className="settings-section-title">{t('pwa.install.title')}</h3>
      {standalone ? (
        <div className="settings-row">
          <div className="settings-value">{t('pwa.install.installed')}</div>
        </div>
      ) : (
        <>
          <div className="settings-row">
            <button
              type="button"
              className="btn btn-primary"
              disabled={!installable}
              onClick={async () => {
                const outcome = await requestInstall();
                setInstallOutcome(outcome);
              }}
            >
              {t('pwa.install.button')}
            </button>
          </div>
          <div className="settings-row">
            <div className="settings-value">
              {installOutcome === 'dismissed' ? t('pwa.install.prompt_hint') : ''}
              {installable ? t('pwa.install.prompt_hint') : t('pwa.install.not_supported')}
              {' '}
              {t('pwa.install.ios_hint')}
            </div>
          </div>
        </>
      )}

      <h3 className="settings-section-title">{t('pwa.offline.title')}</h3>
      <div className="settings-row">
        <div className="settings-value">
          <span className={`status-dot ${online ? 'status-dot-ok' : 'status-dot-warn'}`} aria-hidden="true" />{' '}
          {online ? t('pwa.offline.online') : t('pwa.offline.offline')}
        </div>
      </div>
      <div className="settings-row">
        <div className="settings-value">
          {swState === 'ready'
            ? t('pwa.offline.sw_ready')
            : swState === 'pending'
              ? t('pwa.offline.sw_pending')
              : t('pwa.offline.sw_none')}
        </div>
      </div>
      <p className="settings-label">{t('pwa.offline.first_use')}</p>

      <h3 className="settings-section-title">{t('pwa.download.title')}</h3>
      <p className="settings-label">{t('pwa.download.hint')}</p>
      <div className="settings-row">
        <button
          type="button"
          className="btn"
          onClick={() => {
            void downloadStarter()
              .then(() => setDownloaded(true))
              .catch(() => setDownloaded(false));
          }}
        >
          {t('pwa.download.button')}
        </button>
        {downloaded && <span className="tag tag-success">{t('pwa.download.done')}</span>}
      </div>

      <h3 className="settings-section-title">{t('pwa.network.title')}</h3>
      <p className="settings-label">{t('pwa.network.hint')}</p>
      <ul className="settings-value" style={{ margin: 0, paddingLeft: '1.2em' }}>
        {NETWORK_RESOURCES.map((r) => (
          <li key={r.id}>
            {t(r.labelKey)} — <span className="empty-hint">{t(r.reasonKey)}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

export default PwaPanel;
