// ==========================================================================
// Fun plugin: Barnsley Fern (巴恩斯利蕨)
//
// Iterated Function System that draws a fern from a few affine transforms.
// Pure Canvas 2D; no data input required.
// ==========================================================================

import type {
  ParamDefinition,
  Plugin,
  PluginApi,
  PluginManifest,
  ContainerCapabilities,
} from '@/types/plugin';

export const barnsleyManifest: PluginManifest = {
  id: 'fun.barnsley',
  name: 'Barnsley Fern',
  nameI18n: { 'zh-CN': '巴恩斯利蕨', 'en-US': 'Barnsley Fern' },
  version: '1.0.0',
  author: 'Ergalics',
  description: 'Iterated Function System drawing a fern from four transforms.',
  descriptionI18n: {
    'zh-CN': '用迭代函数系统（IFS）的四个仿射变换绘出蕨类植物。',
    'en-US': 'A fern generated by four affine transforms (Iterated Function System).',
  },
  license: 'MIT',
  entry: 'fun.barnsley',
  category: 'fun',
  icon: '✽',
};

interface State {
  points: number;
  color: string;
  seed: number;
}

// Classic Barnsley fern transforms: (a, b, c, d, e, f, probability).
const TRANSFORMS: Array<[number, number, number, number, number, number, number]> = [
  [0, 0, 0, 0.16, 0, 0, 0.01],
  [0.85, 0.04, -0.04, 0.85, 0, 1.6, 0.85],
  [0.2, -0.26, 0.23, 0.22, 0, 1.6, 0.07],
  [-0.15, 0.28, 0.26, 0.24, 0, 0.44, 0.07],
];

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a += 0x6d2b79f5;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export class BarnsleyPlugin implements Plugin {
  readonly manifest = barnsleyManifest;
  private ctx: ContainerCapabilities | null = null;
  private state: State = { points: 60_000, color: '#6ee7b7', seed: 1 };

  async init(_api: PluginApi) {}

  async destroy() {
    this.ctx = null;
  }

  async activate(context: { container: ContainerCapabilities }) {
    this.ctx = context.container;
    this.draw();
  }

  async deactivate() {}

  render(container: ContainerCapabilities) {
    this.ctx = container;
    this.draw();
  }

  updateParams(params: Record<string, unknown>) {
    if (typeof params.points === 'number') {
      this.state.points = Math.max(2_000, Math.min(300_000, Math.round(params.points)));
    }
    if (typeof params.color === 'string') this.state.color = params.color;
    if (typeof params.seed === 'number') this.state.seed = Math.round(params.seed);
    const reseed = params.regenerate as { action?: string } | undefined;
    if (reseed?.action === 'regenerate') this.state.seed = (this.state.seed + 1) % 1_000_000;
    this.draw();
  }

  getParams(): ParamDefinition[] {
    return [
      {
        key: 'points',
        label: 'Points',
        labelI18n: { 'zh-CN': '点数', 'en-US': 'Points' },
        type: 'range',
        min: 2_000,
        max: 300_000,
        step: 1_000,
        value: this.state.points,
      },
      {
        key: 'color',
        label: 'Color',
        labelI18n: { 'zh-CN': '颜色', 'en-US': 'Color' },
        type: 'select',
        options: [
          { value: '#6ee7b7', label: 'Fern', labelI18n: { 'zh-CN': '蕨绿', 'en-US': 'Fern' } },
          { value: '#fcd34d', label: 'Autumn', labelI18n: { 'zh-CN': '秋黄', 'en-US': 'Autumn' } },
          { value: '#c4b5fd', label: 'Lavender', labelI18n: { 'zh-CN': '薰衣草', 'en-US': 'Lavender' } },
          { value: '#fca5a5', label: 'Coral', labelI18n: { 'zh-CN': '珊瑚', 'en-US': 'Coral' } },
        ],
        value: this.state.color,
      },
      {
        key: 'regenerate',
        label: 'Regenerate',
        labelI18n: { 'zh-CN': '重新生成', 'en-US': 'Regenerate' },
        type: 'button',
        variant: 'primary',
        action: 'regenerate',
      },
    ];
  }

  private draw() {
    const canvas = this.ctx?.canvas2d;
    if (!canvas) return;
    const w = canvas.width = canvas.clientWidth || 480;
    const h = canvas.height = canvas.clientHeight || 360;
    const g = canvas.getContext('2d');
    if (!g) return;
    g.fillStyle = getComputedStyle(canvas).backgroundColor || '#0a0e13';
    g.fillRect(0, 0, w, h);

    const rand = mulberry32(this.state.seed * 7919 + 13);
    // Deterministic LCG for transform selection.
    let a = (this.state.seed * 2654435761) >>> 0;
    const pick = () => {
      a = (a * 1664525 + 1013904223) >>> 0;
      return a / 4294967296;
    };

    // Map fern coordinates (x in [-2.2, 2.7], y in [0, 10.4]) to canvas.
    const scaleX = (w - 40) / 4.9;
    const scaleY = (h - 60) / 10.4;
    const ox = (w - 40) / 2 + 20;
    const oy = 30;

    let x = 0;
    let y = 0;
    g.fillStyle = this.state.color;
    const radius = Math.max(1, Math.min(1.6, Math.sqrt(w * h) / 900));
    for (let i = 0; i < this.state.points; i += 1) {
      const r = pick();
      let cum = 0;
      let tx = TRANSFORMS[0]!;
      for (const tr of TRANSFORMS) {
        cum += tr[6]!;
        if (r <= cum) { tx = tr; break; }
      }
      const [aa, bb, cc, dd, ee, ff] = tx!;
      const nx = aa * x + bb * y + ee;
      const ny = cc * x + dd * y + ff;
      x = nx;
      y = ny;
      // Warm-up iterations avoid the fixed point.
      if (i < 10) continue;
      const px = ox + x * scaleX;
      const py = oy + (10.4 - y) * scaleY;
      // Slight alpha jitter keeps dense areas from blowing out.
      g.globalAlpha = 0.5 + rand() * 0.5;
      g.fillRect(px, py, radius, radius);
    }
    g.globalAlpha = 1;
  }
}

export default function createBarnsleyPlugin(): Plugin {
  return new BarnsleyPlugin();
}
