// ==========================================================================
// Barnsley Fern manifest — pure data, split from the plugin file so
// builtin/index.ts can import it statically without dragging the plugin
// implementation (and its dependency graph) into the first-screen bundle.
// ==========================================================================

import type { PluginManifest } from '@/types/plugin';

export const barnsleyManifest: PluginManifest = {
  id: 'fun.barnsley',
  name: 'Barnsley Fern',
  nameI18n: { 'zh-CN': '巴恩斯利蕨', 'en-US': 'Barnsley Fern' },
  version: '1.0.0',
  author: 'Ergalics',
  description: 'Iterated Function System drawing a fern from four transforms.',
  descriptionI18n: {
    'zh-CN': '用迭代函数系统（IFS）的四个仿射变换绘出蕨类植物。',
    'en-US': 'A fern generated by four affine transforms (Iterated Function System).',
  },
  license: 'MIT',
  entry: 'fun.barnsley',
  category: 'fun',
  icon: '✽',
};
